/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.darkredgm.formulariogui;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.net.MalformedURLException;

/**
 *
 * @author crisv
 */
public class App extends javax.swing.JFrame {

    FormData data;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    private int xMouse = 0, yMourse = 0;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();

        updateButtonStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldGender = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnPanelClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelBasic = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldNumber = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fieldDay = new javax.swing.JComboBox<>();
        fieldMonth = new javax.swing.JComboBox<>();
        fieldYear = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        optionMale = new javax.swing.JRadioButton();
        optionFemale = new javax.swing.JRadioButton();
        panelAddon = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        fieldDireccion = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fieldImageUrl = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnSelecImage = new javax.swing.JButton();
        checkTerminosCondiciones = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/side_dos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, 302, 501));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanelClose.setBackground(new java.awt.Color(255, 255, 255));
        btnPanelClose.setPreferredSize(new java.awt.Dimension(40, 40));

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMinimumSize(new java.awt.Dimension(40, 40));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnPanelCloseLayout = new javax.swing.GroupLayout(btnPanelClose);
        btnPanelClose.setLayout(btnPanelCloseLayout);
        btnPanelCloseLayout.setHorizontalGroup(
            btnPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCloseLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btnPanelCloseLayout.setVerticalGroup(
            btnPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.add(btnPanelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        panelMain.setLayout(new java.awt.CardLayout());

        panelBasic.setBackground(new java.awt.Color(255, 255, 255));
        panelBasic.setName(""); // NOI18N
        panelBasic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre");
        jLabel2.setToolTipText("");
        jPanel6.add(jLabel2);

        fieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldName.setBorder(null);
        fieldName.addActionListener(this::fieldNameActionPerformed);
        jPanel6.add(fieldName);

        jSeparator1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.add(jSeparator1);

        panelBasic.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 351, 70));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Telefono");
        jLabel3.setToolTipText("");
        jPanel7.add(jLabel3);

        fieldNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldNumber.setBorder(null);
        fieldNumber.addActionListener(this::fieldNumberActionPerformed);
        jPanel7.add(fieldNumber);

        jSeparator2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel7.add(jSeparator2);

        panelBasic.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 351, 70));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fecha Nacimiento");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        fieldDay.setBackground(new java.awt.Color(255, 255, 255));
        fieldDay.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        fieldDay.setBorder(null);

        fieldMonth.setBackground(new java.awt.Color(255, 255, 255));
        fieldMonth.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        fieldMonth.setBorder(null);

        fieldYear.setBackground(new java.awt.Color(255, 255, 255));
        fieldYear.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        fieldYear.setBorder(null);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(fieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelBasic.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 314, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Genero");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        optionMale.setBackground(new java.awt.Color(255, 255, 255));
        fieldGender.add(optionMale);
        optionMale.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        optionMale.setText("Masculino");

        optionFemale.setBackground(new java.awt.Color(255, 255, 255));
        fieldGender.add(optionFemale);
        optionFemale.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        optionFemale.setText("Femenino");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(optionMale)
                        .addGap(29, 29, 29)
                        .addComponent(optionFemale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionMale)
                    .addComponent(optionFemale))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBasic.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 238, 351, -1));

        panelMain.add(panelBasic, "panelBasic");
        panelBasic.getAccessibleContext().setAccessibleName("panelBasic");

        panelAddon.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        fieldDireccion.setColumns(20);
        fieldDireccion.setRows(5);
        jPanel8.add(fieldDireccion);

        jSeparator3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel8.add(jSeparator3);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Dirección");
        jLabel8.setToolTipText("");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Imagen");
        jLabel9.setToolTipText("");
        jPanel9.add(jLabel9);

        fieldImageUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldImageUrl.setBorder(null);
        fieldImageUrl.addActionListener(this::fieldImageUrlActionPerformed);
        jPanel9.add(fieldImageUrl);

        jSeparator4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel9.add(jSeparator4);

        btnSelecImage.setBackground(new java.awt.Color(255, 255, 255));
        btnSelecImage.setForeground(new java.awt.Color(153, 0, 0));
        btnSelecImage.setText("Seleccionar Imagen");
        btnSelecImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btnSelecImage.addActionListener(this::btnSelecImageActionPerformed);

        checkTerminosCondiciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkTerminosCondiciones.setText("Acepto los terminos y condiciones");
        checkTerminosCondiciones.setBorder(null);

        javax.swing.GroupLayout panelAddonLayout = new javax.swing.GroupLayout(panelAddon);
        panelAddon.setLayout(panelAddonLayout);
        panelAddonLayout.setHorizontalGroup(
            panelAddonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddonLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelAddonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelecImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkTerminosCondiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAddonLayout.setVerticalGroup(
            panelAddonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddonLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSelecImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkTerminosCondiciones)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelMain.add(panelAddon, "panelAddon");

        bg.add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnPrev.setBackground(new java.awt.Color(255, 255, 255));
        btnPrev.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(153, 0, 0));
        btnPrev.setText("ANTERIOR");
        btnPrev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btnPrev.addActionListener(this::btnPrevActionPerformed);

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnNext.setForeground(new java.awt.Color(153, 0, 0));
        btnNext.setText("SIGUIENTE");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnSubmit.setBackground(new java.awt.Color(153, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("ENVIAR");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        bg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 486, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonStatus() {

        if (panelBasic.isVisible()) {
            btnPrev.setVisible(false);
            btnSubmit.setVisible(false);
        } else {
            btnPrev.setVisible(true);
        }

        if (panelAddon.isVisible()) {
            btnNext.setVisible(false);
            btnSubmit.setVisible(true);
        } else {
            btnNext.setVisible(true);
        }
    }

    private boolean checkFieldStatus() {
        if (fieldName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio", "Error: Nombre", JOptionPane.ERROR_MESSAGE);
            fieldName.requestFocus();
            return false;
        }

        if (fieldNumber.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El teléfono es obligatorio", "Error: Teléfono", JOptionPane.ERROR_MESSAGE);
            fieldNumber.requestFocus();
            return false;
        }

        if (fieldGender.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Selecciona tu género", "Error: Género", JOptionPane.ERROR_MESSAGE);
            optionMale.requestFocus();
            return false;
        }

        // Date validation (not empty)
        if (fieldDay.getSelectedIndex() == -1 || fieldMonth.getSelectedIndex() == -1 || fieldYear.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Completa la fecha de nacimiento", "Error: Fecha", JOptionPane.ERROR_MESSAGE);
            fieldDay.requestFocus();
            return false;
        }

        return true;
    }



    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        if (!checkFieldStatus())
            return;

        this.data = new FormData(
                fieldName.getText(),
                fieldNumber.getText(),
                fieldDireccion.getText(),
                fieldGender.getSelection().getActionCommand()
        );

        CardLayout cl = (CardLayout) (panelMain.getLayout());
        cl.show(panelMain, "panelAddon");
        updateButtonStatus();

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if ( fieldDireccion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Coloque su direccion", "Error: Dirección", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ( fieldImageUrl.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Coloque alguna imagen", "Error: Imagen URL", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ( !checkTerminosCondiciones.isSelected() ) {
            JOptionPane.showMessageDialog(this, "Tiene que aceptar los terminos y condiciones", "Error: LEGAL", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        this.data.setImageUrl( fieldImageUrl.getText().trim() );

        this.data.setNacimiento(
                fieldDay.getActionCommand(),
                fieldMonth.getActionCommand(),
                fieldYear.getActionCommand()
        );

        new Confirmation( this, true, this.data).setVisible(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumberActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:


        CardLayout cl = (CardLayout) (panelMain.getLayout());
        cl.show(panelMain, "panelBasic");

        updateButtonStatus();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void fieldImageUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldImageUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldImageUrlActionPerformed

    private void btnSelecImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecImageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showDialog(this, "Seleccionar Imagen");
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();

            fieldImageUrl.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelecImageActionPerformed


    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMourse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnPanelClose.setBackground(new Color(153, 0, 0));
        btnClose.setForeground(Color.white);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseReleased

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnPanelClose.setBackground(Color.white);
        btnClose.setForeground(Color.gray);
    }//GEN-LAST:event_btnCloseMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMourse);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel btnPanelClose;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSelecImage;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox checkTerminosCondiciones;
    private javax.swing.JComboBox<String> fieldDay;
    private javax.swing.JTextArea fieldDireccion;
    private javax.swing.ButtonGroup fieldGender;
    private javax.swing.JTextField fieldImageUrl;
    private javax.swing.JComboBox<String> fieldMonth;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JComboBox<String> fieldYear;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton optionFemale;
    private javax.swing.JRadioButton optionMale;
    private javax.swing.JPanel panelAddon;
    private javax.swing.JPanel panelBasic;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
