package com.darkredgm.formulariogui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author crisv
 */
public class Confirmation extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Confirmation.class.getName());

    /**
     * Creates new form Confirmation
     */
    public Confirmation(java.awt.Frame parent, boolean modal, FormData data) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();

        this.name.setText("Nombre: "+data.getNombre() );
        this.direccion.setText("Direccion: "+data.getDireccion() );
        this.phone.setText("Telefono: "+data.getTelefono());
        this.gender.setText("Genero: "+data.getGenero());

        this.fecha.setText("Fecha Nacimiento: "+data.getNacimiento());

        loadImageToLabel( data.getImageUrl() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnPanelClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        name.setText("jLabel1");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, 30));

        phone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phone.setText("jLabel2");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 310, 30));

        gender.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        gender.setText("jLabel3");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 30));

        fecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fecha.setText("jLabel4");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, 30));

        direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccion.setText("jLabel4");
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 310, 30));

        imageLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 390, 400));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(780, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnPanelClose.setBackground(new java.awt.Color(255, 255, 255));
        btnPanelClose.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelCloseMouseExited(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMinimumSize(new java.awt.Dimension(40, 40));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnPanelCloseLayout = new javax.swing.GroupLayout(btnPanelClose);
        btnPanelClose.setLayout(btnPanelCloseLayout);
        btnPanelCloseLayout.setHorizontalGroup(
            btnPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCloseLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btnPanelCloseLayout.setVerticalGroup(
            btnPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCloseLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("RESULTADO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMourse;

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMourse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMourse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnPanelClose.setBackground(new Color(153, 0, 0));
        btnClose.setForeground(Color.white);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnPanelClose.setBackground(Color.white);
        btnClose.setForeground(Color.gray);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseReleased

    private void btnPanelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCloseMouseEntered
        btnPanelClose.setBackground(new Color(153, 0, 0));
        btnClose.setForeground(Color.white);
    }//GEN-LAST:event_btnPanelCloseMouseEntered

    private void btnPanelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCloseMouseExited
        btnPanelClose.setBackground(Color.white);
        btnClose.setForeground(Color.gray);
    }//GEN-LAST:event_btnPanelCloseMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel btnPanelClose;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel gender;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables

    private void loadImageToLabel(String imageUrl) {
        try {
            ImageIcon icon;

            // Verificar si es una url o bien una ruta de archivo
            if (imageUrl.startsWith("http")) {
                icon = new ImageIcon(new java.net.URL(imageUrl));
            } else {
                icon = new ImageIcon(imageUrl);
            }

            // Obtener dimensiones originales
            int imgW = icon.getIconWidth();
            int imgH = icon.getIconHeight();
            int labelW = imageLabel.getWidth() > 0 ? imageLabel.getWidth() : 390;
            int labelH = imageLabel.getHeight() > 0 ? imageLabel.getHeight() : 400;

            // Calculamos la imagen para colocarlo como "contain" en css
            double scale = Math.min((double) labelW / imgW, (double) labelH / imgH);
            int finalW = (int) (imgW * scale);
            int finalH = (int) (imgH * scale);

            // Escalamos la imagen
            Image scaledImage = icon.getImage().getScaledInstance(finalW, finalH, Image.SCALE_DEFAULT);

            imageLabel.setIcon(new ImageIcon(scaledImage));
            imageLabel.setText("");

        } catch (Exception e) {
            imageLabel.setText("Error: " + e.getMessage());
            imageLabel.setIcon(null);
        }
    }
}
